---
kind: pipeline
name: default

services:
  - name: docker
    image: docker:19.03.3-rc1-dind
    privileged: true
    entrypoint:
    - dockerd
    command:
      - --mtu=1440
      - --insecure-registry=registry.ci.svc:5000
    volumes:
      - name: docker-socket
        path: /var/run

steps:
  - name: fetch
    image: docker:git
    commands:
      - git fetch --tags
    when:
      event: tag

  - name: build-and-test
    image: autonomy/build-container:latest
    pull: always
    environment:
      REGISTRY: registry.ci.svc:5000
      PLATFORM: linux/amd64
      BUILDKIT_HOST: ${BUILDKIT_HOST=tcp://buildkitd.ci.svc:1234}
    commands:
      - docker buildx create --driver docker-container --platform linux/amd64 --name local --config hack/buildkit.conf --use
      - make # build everything
      - make frontend PUSH=true  # push only frontend for integration tests
      - make integration
    volumes:
      - name: docker-socket
        path: /var/run
    when:
      event:
        include:
          - pull_request

  - name: build-and-test-and-publish
    image: autonomy/build-container:latest
    pull: always
    environment:
      PLATFORM: linux/amd64
      BUILDKIT_HOST: ${BUILDKIT_HOST=tcp://buildkitd.ci.svc:1234}
      DOCKER_USERNAME:
        from_secret: docker_username
      DOCKER_PASSWORD:
        from_secret: docker_password
    commands:
      - docker buildx create --driver docker-container --platform linux/amd64 --name local --use
      - docker login --username "$${DOCKER_USERNAME}" --password "$${DOCKER_PASSWORD}"
      - make PUSH=true
      - make integration
    volumes:
      - name: docker-socket
        path: /var/run
    when:
      event:
        exclude:
          - pull_request

volumes:
  - name: docker-socket
    temp: {}
---
kind: pipeline
name: notify

clone:
  disable: true

steps:
  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
      channel: proj-talos-maintainers
    when:
      status:
        - success
        - failure

trigger:
  status:
    - success
    - failure

depends_on:
  - default
