---
kind: pipeline
name: default

services:
  - name: docker
    image: docker:19.03.0-rc3-dind
    privileged: true
    command:
      - --dns=8.8.8.8
      - --dns=8.8.4.4
      - --mtu=1440
    volumes:
      - name: docker-socket
        path: /var/run

steps:
  - name: fetch
    image: docker:git
    commands:
      - git fetch --tags
    when:
      event: tag

  - name: build
    image: autonomy/build-container:latest
    pull: always
    commands:
      - make PLATFORM=linux/amd64 PUSH=false
    volumes:
      - name: docker-socket
        path: /var/run

volumes:
  - name: docker-socket
    temp: {}
---
kind: pipeline
name: notify

clone:
  disable: true

steps:
  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
      channel: proj-talos-maint
    when:
      status:
        - success
        - failure

trigger:
  status:
    - success
    - failure

depends_on:
  - default
