---
kind: pipeline
name: default

services:
  - name: docker
    image: docker:19.03.3-rc1-dind
    privileged: true
    entrypoint:
    - dockerd
    command:
      - --mtu=1440
      - --insecure-registry=registry.ci.svc:5000
    volumes:
      - name: docker-socket
        path: /var/run

steps:
  - name: fetch
    image: docker:git
    commands:
      - git fetch --tags
    when:
      event: tag

  - name: build-and-test
    image: autonomy/build-container:latest
    pull: always
    environment:
      PLATFORM: linux/amd64,linux/arm64
      SSH_KEY:
        from_secret: ssh_key
      DOCKER_USERNAME:
        from_secret: docker_username
      DOCKER_PASSWORD:
        from_secret: docker_password
    commands:
      - install-ci-key
      - setup-buildx-amd64-arm64
      - docker login --username "$${DOCKER_USERNAME}" --password "$${DOCKER_PASSWORD}"
      - make # build everything
      - make frontend PUSH=true  # push only frontend for integration tests
      - make integration
    volumes:
      - name: docker-socket
        path: /var/run
    when:
      event:
        include:
          - pull_request

  - name: build-and-test-and-publish
    image: autonomy/build-container:latest
    pull: always
    environment:
      PLATFORM: linux/amd64,linux/arm64
      BUILDKIT_HOST: ${BUILDKIT_HOST=tcp://buildkitd.ci.svc:1234}
      SSH_KEY:
        from_secret: ssh_key
      DOCKER_USERNAME:
        from_secret: docker_username
      DOCKER_PASSWORD:
        from_secret: docker_password
    commands:
      - install-ci-key
      - setup-buildx-amd64-arm64
      - docker login --username "$${DOCKER_USERNAME}" --password "$${DOCKER_PASSWORD}"
      - make PUSH=true
      - make integration
    volumes:
      - name: docker-socket
        path: /var/run
    when:
      event:
        exclude:
          - pull_request

volumes:
  - name: docker-socket
    temp: {}
---
kind: pipeline
name: notify

clone:
  disable: true

steps:
  - name: slack
    image: plugins/slack
    settings:
      link_names: true
      template: |
        {{#if build.pull }}
        *{{#success build.status}}✓ Success{{else}}✕ Fail{{/success}}*: {{ repo.owner }}/{{ repo.name }} - <https://github.com/{{ repo.owner }}/{{ repo.name }}/pull/{{ build.pull }}|Pull Request #{{ build.pull }}>
        {{else}}
        *{{#success build.status}}✓ Success{{else}}✕ Fail{{/success}}: {{ repo.owner }}/{{ repo.name }} - Build #{{ build.number }}* (type: `{{ build.event }}`)
        {{/if}}
        Commit: <https://github.com/{{ repo.owner }}/{{ repo.name }}/commit/{{ build.commit }}|{{ truncate build.commit 8 }}>
        Branch: <https://github.com/{{ repo.owner }}/{{ repo.name }}/commits/{{ build.branch }}|{{ build.branch }}>
        Author: {{ build.author }}
        <{{ build.link }}|Visit build page>
      webhook:
        from_secret: slack_webhook
      channel: proj-talos-maintainers
    when:
      status:
        - success
        - failure

trigger:
  status:
    - success
    - failure

depends_on:
  - default
