---
kind: pipeline
name: default

services:
  - name: docker
    image: docker:19.03.3-rc1-dind
    privileged: true
    entrypoint:
    - dockerd
    command:
      - --dns=8.8.8.8
      - --dns=8.8.4.4
      - --mtu=1440
    volumes:
      - name: docker-socket
        path: /var/run

steps:
  - name: fetch
    image: docker:git
    commands:
      - git fetch --tags
    when:
      event: tag

  - name: build
    image: autonomy/build-container:latest
    pull: always
    commands:
      - docker buildx create --driver docker-container --platform linux/amd64 --name local --use
      - make PLATFORM=linux/amd64 PUSH=false
    volumes:
      - name: docker-socket
        path: /var/run
    when:
      event:
        include:
          - pull_request

  - name: build-and-publish
    image: autonomy/build-container:latest
    pull: always
    environment:
      DOCKER_USERNAME:
        from_secret: docker_username
      DOCKER_PASSWORD:
        from_secret: docker_password
    commands:
      - docker buildx create --driver docker-container --platform linux/amd64 --name local --use
      - docker login --username "$${DOCKER_USERNAME}" --password "$${DOCKER_PASSWORD}"
      - make PLATFORM=linux/amd64 PUSH=true
    volumes:
      - name: docker-socket
        path: /var/run
    when:
      event:
        exclude:
          - pull_request

volumes:
  - name: docker-socket
    temp: {}
---
kind: pipeline
name: notify

clone:
  disable: true

steps:
  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
      channel: proj-talos-maintainers
    when:
      status:
        - success
        - failure

trigger:
  status:
    - success
    - failure

depends_on:
  - default
