---
kind: pipeline
name: default
type: kubernetes

steps:
  - name: setup-ci
    image: autonomy/build-container:latest
    commands:
      - git fetch --tags
      - install-ci-key
      - setup-buildx-amd64-arm64
    volumes:
      - name: docker-socket
        path: /var/run
      - name: docker
        path: /root/.docker/buildx

  - name: build-and-test
    image: autonomy/build-container:latest
    pull: always
    environment:
      PLATFORM: linux/amd64,linux/arm64
      REGISTRY: registry.dev.talos-systems.io
    commands:
      - make PUSH=true
      - make integration
    volumes:
      - name: docker-socket
        path: /var/run
      - name: docker
        path: /root/.docker/buildx
    when:
      event:
        include:
          - pull_request

  - name: build-and-test-and-publish
    image: autonomy/build-container:latest
    pull: always
    environment:
      PLATFORM: linux/amd64,linux/arm64
      GHCR_USERNAME:
        from_secret: ghcr_username
      GHCR_PASSWORD:
        from_secret: ghcr_token
    commands:
      - docker login ghcr.io --username "$${GHCR_USERNAME}" --password "$${GHCR_PASSWORD}"
      - make PUSH=true
      - make integration
    volumes:
      - name: docker-socket
        path: /var/run
      - name: docker
        path: /root/.docker/buildx
    when:
      event:
        exclude:
          - pull_request

volumes:
  - name: docker-socket
    host:
      path: /var/ci-docker
  - name: docker
    temp: {}

---
kind: pipeline
name: notify
type: kubernetes

clone:
  disable: true

steps:
  - name: slack
    image: plugins/slack
    settings:
      link_names: true
      template: |
        {{#if build.pull }}
        *{{#success build.status}}✓ Success{{else}}✕ Fail{{/success}}*: {{ repo.owner }}/{{ repo.name }} - <https://github.com/{{ repo.owner }}/{{ repo.name }}/pull/{{ build.pull }}|Pull Request #{{ build.pull }}>
        {{else}}
        *{{#success build.status}}✓ Success{{else}}✕ Fail{{/success}}: {{ repo.owner }}/{{ repo.name }} - Build #{{ build.number }}* (type: `{{ build.event }}`)
        {{/if}}
        Commit: <https://github.com/{{ repo.owner }}/{{ repo.name }}/commit/{{ build.commit }}|{{ truncate build.commit 8 }}>
        Branch: <https://github.com/{{ repo.owner }}/{{ repo.name }}/commits/{{ build.branch }}|{{ build.branch }}>
        Author: {{ build.author }}
        <{{ build.link }}|Visit build page>
      webhook:
        from_secret: slack_webhook
      channel: proj-talos-maintainers
    when:
      status:
        - success
        - failure

trigger:
  status:
    - success
    - failure

depends_on:
  - default
